import { prisma } from "../../config/prisma.js";
import { Router } from "express";
import { authenticate, type AuthenticatedRequest } from "../../common/middleware/auth.middleware.js";
import { asyncHandler } from "../../common/utils/asyncHandler.js";
import { requireOrgRole } from "../organizations/org.rbac.js";
import { blockDemoWrites } from "../../common/middleware/demoReadOnly.middleware.js";
import { validate } from "../../common/middleware/validate.middleware.js";
import { z } from "zod";
import { issueCommand } from "./issue.schema.js";
import { getIssue, updateIssue } from "./issue.service.js";
import { listIssues, qualityOverview, sourceHealth, listQualityRuns } from "./quality.service.js";
export const qualityRoutes = Router({ mergeParams: true });
qualityRoutes.use(authenticate, requireOrgRole(["OWNER", "ADMIN", "AGENT"]));
const id = (req: AuthenticatedRequest, key: string) => String(req.params[key]);
qualityRoutes.get('/assignees', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await prisma.organizationMember.findMany({ where: { organizationId: id(req, 'orgId'), role: { not: 'CUSTOMER' } }, select: { user: { select: { id: true, name: true } } }, orderBy: { id: 'asc' }, take: 200 }) }); }));
qualityRoutes.get('/overview', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await qualityOverview(req.user!.id, id(req, 'orgId'), req.query) }); }));
qualityRoutes.get('/sources', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await sourceHealth(req.user!.id, id(req, 'orgId'), req.query, Number(req.query.page ?? 1)) }); }));
qualityRoutes.get('/runs', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await listQualityRuns(req.user!.id, id(req, 'orgId'), req.query, Number(req.query.page ?? 1)) }); }));
qualityRoutes.get('/issues', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await listIssues(req.user!.id, id(req, 'orgId'), req.query) }); }));
qualityRoutes.get('/issues/:issueId', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await getIssue(req.user!.id, id(req, 'orgId'), id(req, 'issueId'), Number(req.query.page ?? 1)) }); }));
qualityRoutes.patch('/issues/:issueId', requireOrgRole(["OWNER", "ADMIN"]), blockDemoWrites(), validate(z.object({ body: issueCommand })), asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await updateIssue(req.user!.id, id(req, 'orgId'), id(req, 'issueId'), req.body) }); }));
