import { classifyKnowledgeFailure, operationalFailure, selectedSources, attributedVersions, grouping, normalizeTopic, severity, type SignalRun } from "../modules/knowledge-issues/issue.classification.js";
import { assertIssueTransition } from "../modules/knowledge-issues/issue.policy.js";
import { dateRange } from "../modules/knowledge-issues/issue.schema.js";
const base: SignalRun = { id: "run", topic: "Annual refunds", abstained: false, evidencePolicyVersion: "evidence-v2", outputSnapshot: { evidenceDecision: "ANSWER_SUPPORTED" }, sources: [], evaluation: null };
test.each(["WRONG_KNOWLEDGE", "INSUFFICIENT_KB", "IRRELEVANT_EVIDENCE", "UNSUPPORTED_CLAIM"])("explicit %s is a knowledge signal", reason => { expect(classifyKnowledgeFailure({ ...base, evaluation: { disposition: "REJECTED", reason } })).toBe(reason); });
test.each(["BAD_TONE", "MISSING_CUSTOMER_CONTEXT", "INCORRECT_RECOMMENDATION", "INCOMPLETE_RESPONSE", "OTHER", null])("conservative exclusion: %s", reason => { expect(classifyKnowledgeFailure({ ...base, evaluation: { disposition: "EDITED", reason } })).toBeNull(); });
test.each(["NEEDS_CUSTOMER_INFO", "RETRIEVAL_DEGRADED"])("%s is not knowledge failure even with conflicting feedback", decision => { expect(classifyKnowledgeFailure({ ...base, abstained: true, outputSnapshot: { evidenceDecision: decision }, evaluation: { disposition: "REJECTED", reason: "WRONG_KNOWLEDGE" } })).toBeNull(); });
test.each(["INSUFFICIENT_KNOWLEDGE", "CONFLICTING_KNOWLEDGE"])("deterministic %s abstention counts", decision => { expect(classifyKnowledgeFailure({ ...base, abstained: true, outputSnapshot: { evidenceDecision: decision } })).toBe(decision); });
test("legacy abstention and provider failure alone are not KB defects", () => { expect(classifyKnowledgeFailure({ ...base, abstained: true, evidencePolicyVersion: null })).toBeNull(); const run = { ...base, providerMetadata: { attempts: [{ outcome: "FAILED" }] } }; expect(operationalFailure(run)).toBe(true); expect(classifyKnowledgeFailure(run)).toBeNull(); });
test("source uses deduplicate versions, preserve versions and exclude unselected/legacy chunks", () => { const s = { documentId: "doc", documentVersionId: "v1", documentName: "Refunds", versionNumber: 1, evidenceEligible: true }; const sources = selectedSources([s, s, { ...s, documentVersionId: "v2", versionNumber: 2 }, { ...s, documentVersionId: "v3", evidenceEligible: false }, { documentId: "legacy" }]); expect(sources.map(s => s.documentVersionId)).toEqual(["v1", "v2"]); expect(attributedVersions("WRONG_KNOWLEDGE", sources)).toEqual([]); expect(attributedVersions("CONFLICTING_KNOWLEDGE", sources)).toEqual(["v1", "v2"]); expect(attributedVersions("WRONG_KNOWLEDGE", sources.slice(0, 1))).toEqual(["v1"]); expect(attributedVersions("IRRELEVANT_EVIDENCE", sources.slice(0, 1))).toEqual(["v1"]); for (const r of ["BAD_TONE", "INSUFFICIENT_KB", "UNSUPPORTED_CLAIM", null])
    expect(attributedVersions(r, sources)).toEqual([]); });
test("grouping normalizes noise but keeps problem, failure type and version distinct", () => { const a = grouping(base, "INSUFFICIENT_KB", []); expect(grouping({ ...base, topic: "  Please ANNUAL   refunds!! " }, "INSUFFICIENT_KB", []).key).toBe(a.key); expect(grouping({ ...base, topic: "Monthly refunds" }, "INSUFFICIENT_KB", []).key).not.toBe(a.key); expect(grouping(base, "WRONG_KNOWLEDGE", []).key).not.toBe(a.key); expect(normalizeTopic("ERR-42 Plan_Pro v2.1")).toBe("err-42 plan_pro v2.1"); });
test.each([[1, "LOW"], [2, "LOW"], [3, "MEDIUM"], [5, "MEDIUM"], [6, "HIGH"], [20, "HIGH"]])("severity uses distinct tickets: %s", (count, result) => expect(severity(count as number)).toBe(result));
test.each([["DETECTED", "REVIEWING"], ["REVIEWING", "FIX_PROPOSED"], ["FIX_PROPOSED", "PUBLISHED"], ["PUBLISHED", "REVIEWING"], ["DISMISSED", "REVIEWING"]] as const)("valid transition %s → %s", (from, to) => expect(() => assertIssueTransition(from, to)).not.toThrow());
test.each([["DETECTED", "PUBLISHED"], ["PUBLISHED", "VERIFIED"], ["DETECTED", "VERIFIED"], ["DISMISSED", "FIX_PROPOSED"]] as const)("invalid transition %s → %s", (from, to) => expect(() => assertIssueTransition(from, to)).toThrow());
test("date defaults, bounded ranges and invalid dates", () => { const now = new Date("2026-09-28T12:00:00Z"); expect(dateRange({}, now).from.toISOString()).toBe("2026-08-29T12:00:00.000Z"); expect(dateRange({ days: 7 }, now).from.toISOString()).toBe("2026-09-21T12:00:00.000Z"); for (const input of [{ days: 365 }, { from: "bad", to: "bad" }, { from: "2020-01-01T00:00:00Z", to: now.toISOString() }, { from: now.toISOString() }, { from: now.toISOString(), to: now.toISOString() }, { days: 7, from: "2026-09-01T00:00:00Z", to: now.toISOString() }])
    expect(() => dateRange(input, now)).toThrow(); });
