import { Prisma, type CopilotFailureReason, type CopilotDisposition } from "@prisma/client";
import { prisma } from "../config/prisma.js";
import { createSeedKnowledge } from "../../prisma/seedKnowledge.js";
import { contentHash } from "../common/utils/contentHash.js";
import { deriveKnowledgeSignal, reconcileKnowledgeSignals, getIssue, updateIssue } from "../modules/knowledge-issues/issue.service.js";
import { qualityOverview, sourceHealth, listIssues, listQualityRuns, facts } from "../modules/knowledge-issues/quality.service.js";
import { classifyKnowledgeFailure } from "../modules/knowledge-issues/issue.classification.js";
import { publishKnowledgeVersion } from "../modules/knowledge-base/kb.version.service.js";
import { evaluateCopilotRun, sendCopilotResponse } from "../modules/ai/ai.decision.js";
import { generateAiDraftReply } from "../modules/ai/ai.service.js";
import { updateOrganizationMemberRole, removeOrganizationMember } from "../modules/organizations/org.service.js";
import { qualityRoutes } from "../modules/knowledge-issues/quality.routes.js";
import { signAccessToken } from "../common/utils/jwt.js";
import { errorHandler } from "../common/errors/errorHandler.js";
import express from "express";
import request from "supertest";
const app = express();
app.use(express.json());
app.use('/organizations/:orgId/quality', qualityRoutes);
app.use(errorHandler);
const prefix = 'stage-g-' + Date.now();
let seq = 0;
const orgs: string[] = [], users: string[] = [];
afterAll(async () => { await prisma.organization.deleteMany({ where: { id: { in: orgs } } }); await prisma.user.deleteMany({ where: { id: { in: users } } }); await prisma.$disconnect(); });
async function fixture() { const key = seq++; const people = await Promise.all(['OWNER', 'ADMIN', 'AGENT', 'CUSTOMER'].map(async (role) => { const u = await prisma.user.create({ data: { name: role, email: prefix + key + role + '@test.invalid', passwordHash: 'fixture' } }); users.push(u.id); return u; })); const [owner, admin, agent, customer] = people; const org = await prisma.organization.create({ data: { name: prefix, slug: prefix + key, ownerId: owner.id } }); orgs.push(org.id); await prisma.organizationMember.createMany({ data: people.map((u, i) => ({ organizationId: org.id, userId: u.id, role: (['OWNER', 'ADMIN', 'AGENT', 'CUSTOMER'] as const)[i] })) }); const ticket = await prisma.ticket.create({ data: { organizationId: org.id, customerId: customer.id, title: 'Annual refund eligibility', description: 'Annual plan refund eligibility policy' } }); return { owner, admin, agent, customer, org, ticket }; }
type Fixture = Awaited<ReturnType<typeof fixture>>;
async function publication(f: Fixture) { const document = await createSeedKnowledge(prisma, { data: { organizationId: f.org.id, uploadedById: f.owner.id, fileName: 'policy', originalName: 'Refund Policy', mimeType: 'text/plain', sizeBytes: 100, storagePath: 'fixture', status: 'READY', chunks: { create: [0, 1].map(chunkIndex => ({ organizationId: f.org.id, chunkIndex, tokenCount: 10, content: 'Annual refund eligibility policy. Annual plan refunds require a purchase date. ' + chunkIndex })) } } }); return { document, version: await prisma.knowledgeDocumentVersion.findUniqueOrThrow({ where: { id: document.currentPublishedVersionId! }, include: { chunks: true } }) }; }
async function candidate(f: Fixture, documentId: string) { const text = 'Revised annual refund eligibility policy'; const v = await prisma.knowledgeDocumentVersion.create({ data: { documentId, versionNumber: 2, status: 'READY', originalName: 'Refund v2', mimeType: 'text/plain', sizeBytes: 40, storageRef: 'fixture-v2', createdByIdentity: f.owner.id, contentHash: contentHash(text), semanticIndexedChunks: 0 } }); await prisma.knowledgeChunk.create({ data: { organizationId: f.org.id, documentId, documentVersionId: v.id, chunkIndex: 0, tokenCount: 10, content: text, contentHash: contentHash(text) } }); return v; }
type Options = {
    reason?: CopilotFailureReason;
    disposition?: CopilotDisposition;
    policy?: string;
    ticketId?: string;
    topic?: string;
    publication?: Awaited<ReturnType<typeof publication>>;
    createdAt?: Date;
    legacy?: boolean;
    providerMetadata?: Prisma.InputJsonValue;
};
async function run(f: Fixture, o: Options = {}) { const policy = o.policy ?? 'ANSWER_SUPPORTED'; const sources = o.publication?.version.chunks.map(c => ({ documentId: o.publication!.document.id, documentVersionId: o.publication!.version.id, versionNumber: o.publication!.version.versionNumber, documentName: 'Refund Policy', chunkId: c.id, evidenceEligible: true })) ?? []; return prisma.copilotRun.create({ data: { organizationId: f.org.id, ticketId: o.ticketId ?? f.ticket.id, triggeredById: f.owner.id, provider: 'fallback', confidence: 'LOW', tone: 'PROFESSIONAL', topic: o.topic ?? 'Annual refund eligibility', issueSummary: 'Fixture', missingInformation: [], recommendedAction: 'Review', suggestedReply: policy === 'ANSWER_SUPPORTED' ? 'Fixture reply' : null, abstained: policy !== 'ANSWER_SUPPORTED', searchQuery: 'refund', searchMode: 'keyword', sourceCount: sources.length, sources, warnings: [], evidencePolicyVersion: o.legacy ? null : 'evidence-v2', outputSnapshot: { evidenceDecision: policy }, providerMetadata: o.providerMetadata, createdAt: o.createdAt, knowledgeSources: { create: sources.map(s => ({ documentVersionId: s.documentVersionId, chunkId: s.chunkId })) }, ...(o.reason || o.disposition ? { evaluation: { create: { evaluatorId: f.owner.id, disposition: o.disposition ?? 'REJECTED', reason: o.reason } } } : {}) }, include: { evaluation: true } }); }
async function detected(f: Fixture) { const r = await run(f, { reason: 'INSUFFICIENT_KB' }); const result = await deriveKnowledgeSignal(f.org.id, r.id); return result.issueId!; }
test('concurrent ingestion is idempotent; normalized problems group but distinct tickets count once', async () => { const f = await fixture(); const a = await run(f, { reason: 'INSUFFICIENT_KB' }); await Promise.all([deriveKnowledgeSignal(f.org.id, a.id), deriveKnowledgeSignal(f.org.id, a.id)]); const b = await run(f, { reason: 'INSUFFICIENT_KB', topic: 'Please ANNUAL refund eligibility!!' }); await deriveKnowledgeSignal(f.org.id, b.id); const ticket = await prisma.ticket.create({ data: { organizationId: f.org.id, customerId: f.customer.id, title: 'Another ticket', description: 'Annual refunds' } }); const c = await run(f, { reason: 'INSUFFICIENT_KB', ticketId: ticket.id }); await deriveKnowledgeSignal(f.org.id, c.id); const list = await listIssues(f.owner.id, f.org.id); expect(list.issues).toHaveLength(1); expect(list.issues[0]).toMatchObject({ signalCount: 3, affectedTicketCount: 2, severity: 'LOW' }); await run(f, { reason: 'INSUFFICIENT_KB', topic: 'Monthly billing error' }); expect((await reconcileKnowledgeSignals(f.org.id)).created).toBe(1); expect((await reconcileKnowledgeSignals(f.org.id)).created).toBe(0); expect((await listIssues(f.owner.id, f.org.id)).issues).toHaveLength(2); });
test('bounded backfill discovers late decisions and keeps tenants separate', async () => { const f = await fixture(), other = await fixture(); const a = await run(f), b = await run(f, { reason: 'WRONG_KNOWLEDGE' }), c = await run(other, { reason: 'WRONG_KNOWLEDGE' }); const batch = await reconcileKnowledgeSignals(f.org.id, undefined, 1); expect(batch.scanned).toBe(1); expect(batch.nextCursor).not.toBeNull(); await reconcileKnowledgeSignals(f.org.id, batch.nextCursor!, 1); await prisma.copilotEvaluation.create({ data: { copilotRunId: a.id, evaluatorId: f.owner.id, disposition: 'REJECTED', reason: 'INSUFFICIENT_KB' } }); expect((await reconcileKnowledgeSignals(f.org.id)).created).toBe(1); expect(await prisma.knowledgeIssueSignal.count({ where: { copilotRunId: { in: [a.id, b.id] } } })).toBe(2); expect(await prisma.knowledgeIssueSignal.count({ where: { copilotRunId: c.id } })).toBe(0); await expect(deriveKnowledgeSignal(other.org.id, a.id)).rejects.toMatchObject({ statusCode: 404 }); });
test('source attribution is one use per version/run and separates bad tone, gaps, wrong knowledge and relevance', async () => { const f = await fixture(), p = await publication(f); for (const o of [{ disposition: 'ACCEPTED' }, { disposition: 'EDITED', reason: 'BAD_TONE' }, { reason: 'WRONG_KNOWLEDGE' }, { reason: 'IRRELEVANT_EVIDENCE' }, { reason: 'UNSUPPORTED_CLAIM' }, { reason: 'INSUFFICIENT_KB' }, { policy: 'RETRIEVAL_DEGRADED' }] as Options[])
    await run(f, { ...o, publication: p }); await run(f, { policy: 'INSUFFICIENT_KNOWLEDGE' }); await reconcileKnowledgeSignals(f.org.id); const health = (await sourceHealth(f.owner.id, f.org.id)).sources[0]; expect(health).toMatchObject({ runsUsingSource: 7, evaluatedRuns: 6, acceptedRuns: 1, editedRuns: 1, rejectedRuns: 4, knowledgeFailureRuns: 2, wrongKnowledgeRuns: 1, irrelevantEvidenceRuns: 1, limitedData: true }); expect(health.observedFailureRate).toEqual({ numerator: 2, denominator: 6, percent: 33.3 }); const overview = await qualityOverview(f.owner.id, f.org.id); expect(overview).toMatchObject({ totalRuns: 8, evaluatedRuns: 6, knowledgeFailures: 5, operationalFailures: 1, affectedTickets: 1 }); expect(overview.evaluationCoverage).toEqual({ numerator: 6, denominator: 8, percent: 75 }); });
test('source versions have independent observations after publication', async () => { const f = await fixture(), p = await publication(f); await run(f, { reason: 'WRONG_KNOWLEDGE', publication: p }); const v2 = await candidate(f, p.document.id); await publishKnowledgeVersion(f.owner.id, f.org.id, p.document.id, v2.id, p.version.id); const latest = { document: p.document, version: await prisma.knowledgeDocumentVersion.findUniqueOrThrow({ where: { id: v2.id }, include: { chunks: true } }) }; await run(f, { disposition: 'ACCEPTED', publication: latest }); const health = (await sourceHealth(f.owner.id, f.org.id)).sources; expect(health.find(s => s.versionId === p.version.id)).toMatchObject({ isCurrent: false, knowledgeFailureRuns: 1 }); expect(health.find(s => s.versionId === v2.id)).toMatchObject({ isCurrent: true, knowledgeFailureRuns: 0, acceptedRuns: 1 }); });
test('workflow links a READY fix, records actual publication deliberately and never permits VERIFIED', async () => { const f = await fixture(), issueId = await detected(f), p = await publication(f), v = await candidate(f, p.document.id); let issue = await updateIssue(f.owner.id, f.org.id, issueId, { expectedRevision: 0, status: 'REVIEWING', assignedToUserId: f.agent.id }); issue = await updateIssue(f.admin.id, f.org.id, issueId, { expectedRevision: issue.revision, status: 'FIX_PROPOSED', candidateVersionId: v.id, note: 'Clarifies annual eligibility' }); await expect(updateIssue(f.owner.id, f.org.id, issueId, { expectedRevision: issue.revision, status: 'PUBLISHED' })).rejects.toMatchObject({ statusCode: 409 }); await publishKnowledgeVersion(f.owner.id, f.org.id, p.document.id, v.id, p.version.id); const detail = await getIssue(f.agent.id, f.org.id, issueId); expect(detail.candidateVersion?.publishedAt).not.toBeNull(); expect(detail.status).toBe('FIX_PROPOSED'); issue = await updateIssue(f.owner.id, f.org.id, issueId, { expectedRevision: issue.revision, status: 'PUBLISHED' }); await expect(updateIssue(f.owner.id, f.org.id, issueId, { expectedRevision: issue.revision, status: 'VERIFIED' })).rejects.toMatchObject({ statusCode: 409 }); expect((await getIssue(f.owner.id, f.org.id, issueId)).history.map(h => h.event)).toContain('CANDIDATE_PUBLICATION_RECORDED'); });
test('dismissal retains signals and records actor/reason; recurrence needs deliberate review', async () => { const f = await fixture(), id = await detected(f); await updateIssue(f.owner.id, f.org.id, id, { expectedRevision: 0, status: 'DISMISSED', dismissalReason: 'EXPECTED_BEHAVIOR', note: 'Reviewed against policy' }); const r = await run(f, { reason: 'INSUFFICIENT_KB' }); await deriveKnowledgeSignal(f.org.id, r.id); const detail = await getIssue(f.owner.id, f.org.id, id); expect(detail).toMatchObject({ status: 'DISMISSED', dismissalReason: 'EXPECTED_BEHAVIOR', dismissedByIdentity: f.owner.id, signalCount: 2 }); await updateIssue(f.owner.id, f.org.id, id, { expectedRevision: 1, status: 'REVIEWING' }); });
test('optimistic revisions prevent conflicting workflow changes and assignment revokes on demotion', async () => { const f = await fixture(), id = await detected(f); const results = await Promise.allSettled([updateIssue(f.owner.id, f.org.id, id, { expectedRevision: 0, status: 'REVIEWING', assignedToUserId: f.agent.id }), updateIssue(f.admin.id, f.org.id, id, { expectedRevision: 0, status: 'REVIEWING', assignedToUserId: f.agent.id })]); expect(results.filter(r => r.status === 'fulfilled')).toHaveLength(1); const member = await prisma.organizationMember.findUniqueOrThrow({ where: { organizationId_userId: { organizationId: f.org.id, userId: f.agent.id } } }); await updateOrganizationMemberRole(f.owner.id, f.org.id, member.id, { role: 'CUSTOMER' }); expect((await getIssue(f.owner.id, f.org.id, id)).assignee).toBeNull(); expect((await getIssue(f.owner.id, f.org.id, id)).history.some(h => h.event === 'ASSIGNMENT_REVOKED')).toBe(true); });
test('customer, agent mutation, cross-tenant candidates and assignees are denied', async () => { const f = await fixture(), other = await fixture(), id = await detected(f), p = await publication(other), v = await candidate(other, p.document.id); await expect(getIssue(f.customer.id, f.org.id, id)).rejects.toMatchObject({ statusCode: 403 }); await expect(getIssue(other.owner.id, other.org.id, id)).rejects.toMatchObject({ statusCode: 404 }); await expect(sourceHealth(other.owner.id, f.org.id)).rejects.toMatchObject({ statusCode: 403 }); await expect(updateIssue(f.agent.id, f.org.id, id, { expectedRevision: 0, status: 'REVIEWING' })).rejects.toMatchObject({ statusCode: 403 }); await expect(updateIssue(f.owner.id, f.org.id, id, { expectedRevision: 0, assignedToUserId: other.agent.id })).rejects.toMatchObject({ statusCode: 400 }); await updateIssue(f.owner.id, f.org.id, id, { expectedRevision: 0, status: 'REVIEWING' }); await expect(updateIssue(f.owner.id, f.org.id, id, { expectedRevision: 1, status: 'FIX_PROPOSED', candidateVersionId: v.id, note: 'Invalid' })).rejects.toMatchObject({ statusCode: 400 }); await expect(prisma.knowledgeIssue.update({ where: { id }, data: { candidateVersionId: v.id } })).rejects.toThrow(); const r = await run(other, { reason: 'INSUFFICIENT_KB' }); await expect(prisma.knowledgeIssueSignal.create({ data: { issueId: id, copilotRunId: r.id, reason: 'INSUFFICIENT_KB', classifierVersion: 'test', occurredAt: new Date() } })).rejects.toThrow(); });
test('HTTP staff reads are scoped, customer access and demo mutation are denied, dates validate', async () => { const f = await fixture(), id = await detected(f), root = '/organizations/' + f.org.id + '/quality'; const owner = { Authorization: 'Bearer ' + signAccessToken(f.owner.id) }; await request(app).get(root + '/overview').expect(401); await request(app).get(root + '/overview').set('Authorization', 'Bearer ' + signAccessToken(f.customer.id)).expect(403); await request(app).get(root + '/sources').set('Authorization', 'Bearer ' + signAccessToken(f.agent.id)).expect(200); await request(app).get(root + '/overview?days=365').set(owner).expect(400); await request(app).patch(root + '/issues/' + id).set('Authorization', 'Bearer ' + signAccessToken(f.agent.id)).send({ expectedRevision: 0, status: 'REVIEWING' }).expect(403); const previous = process.env.DEMO_READONLY_EMAILS; process.env.DEMO_READONLY_EMAILS = f.owner.email; try {
    await request(app).patch(root + '/issues/' + id).set(owner).send({ expectedRevision: 0, status: 'REVIEWING' }).expect(403);
}
finally {
    if (previous === undefined)
        delete process.env.DEMO_READONLY_EMAILS;
    else
        process.env.DEMO_READONLY_EMAILS = previous;
} });
test('date semantics filter by run creation, safe empty periods, legacy JSON and SQL classifier parity', async () => { const f = await fixture(); await run(f, { reason: 'WRONG_KNOWLEDGE', createdAt: new Date(Date.now() - 40 * 86400000) }); const inputs: Options[] = [{ reason: 'WRONG_KNOWLEDGE' }, { policy: 'NEEDS_CUSTOMER_INFO' }, { policy: 'RETRIEVAL_DEGRADED' }, { policy: 'INSUFFICIENT_KNOWLEDGE' }, { policy: 'CONFLICTING_KNOWLEDGE' }, { legacy: true, policy: 'OLD' }, { providerMetadata: { attempts: [{ outcome: 'FAILED' }] } }]; const records = []; for (const o of inputs)
    records.push(await run(f, o)); const q = await qualityOverview(f.owner.id, f.org.id, { days: 7 }); expect(q.totalRuns).toBe(inputs.length); expect(q.evaluationCoverage).toMatchObject({ numerator: 1, denominator: 7 }); expect(q.operationalFailures).toBe(2); const range = { from: new Date(Date.now() - 7 * 86400000), to: new Date() }; const sql = await prisma.$queryRaw<Array<{
    id: string;
    knowledgeReason: string | null;
}>> `${facts(f.org.id, range)} SELECT id,"knowledgeReason" FROM facts`; for (const r of records)
    expect(sql.find(s => s.id === r.id)?.knowledgeReason).toBe(classifyKnowledgeFailure(r)); const empty = await qualityOverview(f.owner.id, f.org.id, { from: '2020-01-01T00:00:00Z', to: '2020-01-02T00:00:00Z' }); expect(empty.evaluationCoverage).toEqual({ numerator: 0, denominator: 0, percent: 0 }); expect((await listQualityRuns(f.owner.id, f.org.id, { days: 7 })).runs).toHaveLength(7); });
test('post-commit issue failure cannot undo a terminal decision, and reconciliation repairs it', async () => { const f = await fixture(), r = await run(f); await prisma.$executeRawUnsafe("CREATE FUNCTION stage_g_fail_issue() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected'; END $$"); await prisma.$executeRawUnsafe('CREATE TRIGGER stage_g_fail_issue BEFORE INSERT ON "KnowledgeIssueSignal" FOR EACH ROW EXECUTE FUNCTION stage_g_fail_issue()'); try {
    const evaluation = await evaluateCopilotRun(f.owner.id, f.ticket.id, r.id, { disposition: 'REJECTED', reason: 'WRONG_KNOWLEDGE' });
    expect(evaluation.disposition).toBe('REJECTED');
    expect(await prisma.knowledgeIssueSignal.count({ where: { copilotRunId: r.id } })).toBe(0);
}
finally {
    await prisma.$executeRawUnsafe('DROP TRIGGER stage_g_fail_issue ON "KnowledgeIssueSignal"');
    await prisma.$executeRawUnsafe('DROP FUNCTION stage_g_fail_issue()');
} expect((await reconcileKnowledgeSignals(f.org.id)).created).toBe(1); expect((await reconcileKnowledgeSignals(f.org.id)).created).toBe(0); });
test('post-commit analytics read failure cannot fail an already persisted customer reply', async () => { const f = await fixture(); await publication(f); await prisma.ticket.update({ where: { id: f.ticket.id }, data: { description: 'Annual plan refund eligibility. Purchase date 2026-09-01' } }); const draft = await generateAiDraftReply(f.owner.id, f.ticket.id, { tone: 'PROFESSIONAL' }); expect(draft.abstained).toBe(false); const spy = jest.spyOn(prisma.copilotRun, 'findUnique').mockRejectedValueOnce(new Error('analytics unavailable')); try {
    const result = await sendCopilotResponse(f.owner.id, f.ticket.id, draft.runId!, { finalMessage: draft.suggestedReply! });
    expect(result.message?.body).toBe(draft.suggestedReply);
    expect(await prisma.ticketMessage.count({ where: { id: result.message!.id } })).toBe(1);
}
finally {
    spy.mockRestore();
} });
test('top issues and severity use unique affected tickets, not repeated experiments', async () => {
    const f = await fixture();
    for (let i = 0; i < 6; i++) {
        const t = await prisma.ticket.create({ data: { organizationId: f.org.id, customerId: f.customer.id, title: 'Affected ' + i, description: 'Refund' } });
        await run(f, { reason: 'INSUFFICIENT_KB', ticketId: t.id });
    }
    for (let i = 0; i < 8; i++)
        await run(f, { reason: 'INSUFFICIENT_KB', topic: 'Repeated single-ticket experiment' });
    await reconcileKnowledgeSignals(f.org.id);
    const list = await listIssues(f.agent.id, f.org.id);
    expect(list.issues[0]).toMatchObject({ severity: 'HIGH', affectedTicketCount: 6, signalCount: 6 });
    expect(list.issues[1]).toMatchObject({ severity: 'LOW', affectedTicketCount: 1, signalCount: 8 });
    expect((await listIssues(f.agent.id, f.org.id, { severity: 'HIGH' })).issues).toHaveLength(1);
});

test('issue audit failure rolls back status, assignment and revision together', async()=>{
 const f=await fixture(),id=await detected(f);
 await prisma.$executeRawUnsafe("CREATE FUNCTION stage_g_fail_history() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event='STATUS_CHANGED' THEN RAISE EXCEPTION 'injected'; END IF; RETURN NEW; END $$");
 await prisma.$executeRawUnsafe('CREATE TRIGGER stage_g_fail_history BEFORE INSERT ON "KnowledgeIssueHistory" FOR EACH ROW EXECUTE FUNCTION stage_g_fail_history()');
 try {await expect(updateIssue(f.owner.id,f.org.id,id,{expectedRevision:0,status:'REVIEWING',assignedToUserId:f.agent.id})).rejects.toThrow();}
 finally{await prisma.$executeRawUnsafe('DROP TRIGGER stage_g_fail_history ON "KnowledgeIssueHistory"');await prisma.$executeRawUnsafe('DROP FUNCTION stage_g_fail_history()');}
 expect(await prisma.knowledgeIssue.findUnique({where:{id}})).toMatchObject({status:'DETECTED',revision:0,assigneeMemberId:null});
});
