import * as realtime from "../modules/realtime/realtime.service.js";
import { prisma } from '../config/prisma.js';
import { createSeedKnowledge } from '../../prisma/seedKnowledge.js';
import { contentHash } from '../common/utils/contentHash.js';
import { createSuite, createExperiment, getExperiment, issueCohort } from '../modules/reliability/replay.service.js';
import { executeExperiment, cancelExperiment, verifyIssue } from '../modules/reliability/replay.execution.js';
import { deriveKnowledgeSignal, updateIssue } from '../modules/knowledge-issues/issue.service.js';
import { publishKnowledgeVersion } from '../modules/knowledge-base/kb.version.service.js';
import { retrieveHybrid } from '../modules/knowledge-base/kb.hybrid.js';
import * as provider from '../modules/ai/ai.provider.js';
import * as vector from '../modules/knowledge-base/kb.vector.js';
import * as lexical from '../modules/knowledge-base/kb.lexical.js';
const prefix = 'stage-h-' + Date.now();
let seq = 0;
const orgs: string[] = [], users: string[] = [];
afterAll(async () => { await prisma.organization.deleteMany({ where: { id: { in: orgs } } }); await prisma.user.deleteMany({ where: { id: { in: users } } }); await prisma.$disconnect(); });
async function fixture() { const key = seq++; const people = await Promise.all(['OWNER', 'ADMIN', 'AGENT', 'CUSTOMER'].map(async (role) => { const u = await prisma.user.create({ data: { name: role, email: prefix + key + role + '@test.invalid', passwordHash: 'fixture' } }); users.push(u.id); return u; })); const [owner, admin, agent, customer] = people; const org = await prisma.organization.create({ data: { name: prefix, slug: prefix + key, ownerId: owner.id } }); orgs.push(org.id); await prisma.organizationMember.createMany({ data: people.map((u, i) => ({ organizationId: org.id, userId: u.id, role: (['OWNER', 'ADMIN', 'AGENT', 'CUSTOMER'] as const)[i] })) }); const ticket = await prisma.ticket.create({ data: { organizationId: org.id, customerId: customer.id, title: 'Annual refund eligibility', description: 'Annual plan refund eligibility policy' } }); return { owner, admin, agent, customer, org, ticket }; }
type Fixture = Awaited<ReturnType<typeof fixture>>;
async function publication(f: Fixture) { const document = await createSeedKnowledge(prisma, { data: { organizationId: f.org.id, uploadedById: f.owner.id, fileName: 'policy', originalName: 'Refund Policy', mimeType: 'text/plain', sizeBytes: 100, storagePath: 'fixture', status: 'READY', chunks: { create: [0, 1].map(chunkIndex => ({ organizationId: f.org.id, chunkIndex, tokenCount: 10, content: 'Annual refund eligibility policy. Annual plan refunds require a purchase date. ' + chunkIndex })) } } }); return { document, version: await prisma.knowledgeDocumentVersion.findUniqueOrThrow({ where: { id: document.currentPublishedVersionId! }, include: { chunks: true } }) }; }
async function candidate(f: Fixture, documentId: string) { const text = 'Revised annual refund eligibility policy'; const v = await prisma.knowledgeDocumentVersion.create({ data: { documentId, versionNumber: 2, status: 'READY', originalName: 'Refund v2', mimeType: 'text/plain', sizeBytes: 40, storageRef: 'fixture-v2', createdByIdentity: f.owner.id, contentHash: contentHash(text), semanticIndexedChunks: 0 } }); await prisma.knowledgeChunk.create({ data: { organizationId: f.org.id, documentId, documentVersionId: v.id, chunkIndex: 0, tokenCount: 10, content: text, contentHash: contentHash(text) } }); return v; }
async function historical(f: Fixture, accepted = false, query = 'Annual refund eligibility policy') { const p = await prisma.knowledgeDocumentVersion.findFirst({ where: { document: { organizationId: f.org.id }, status: 'PUBLISHED' }, include: { chunks: true } }); return prisma.copilotRun.create({ data: { organizationId: f.org.id, ticketId: f.ticket.id, provider: 'fallback', confidence: 'LOW', tone: 'PROFESSIONAL', topic: 'Annual refund eligibility', issueSummary: 'Seeded history', missingInformation: [], recommendedAction: 'Review', suggestedReply: accepted ? 'Historical response' : null, abstained: !accepted, searchQuery: 'Annual refund eligibility policy', searchMode: 'hybrid', sourceCount: accepted ? 1 : 0, sources: accepted && p ? [{ documentId: p.documentId, documentVersionId: p.id, versionNumber: p.versionNumber, evidenceEligible: true }] : [], warnings: [], provenanceVersion: 1, evidencePolicyVersion: 'evidence-v2', inputSnapshot: { ticket: { title: f.ticket.title, description: f.ticket.description, status: 'OPEN', priority: 'MEDIUM', customerName: 'Customer' }, conversation: [], tone: 'PROFESSIONAL', retrievalQuery: query }, outputSnapshot: { evidenceDecision: accepted ? 'ANSWER_SUPPORTED' : 'INSUFFICIENT_KNOWLEDGE' }, ...(accepted ? { evaluation: { create: { disposition: 'ACCEPTED', finalMessage: 'Historical response' } }, knowledgeSources: { create: p ? [{ documentVersionId: p.id, chunkId: p.chunks[0].id }] : [] } } : {}) } }); }
async function setup() { const f = await fixture(), p = await publication(f), v = await candidate(f, p.document.id), r = await historical(f), g = await historical(f, true); const issueId = (await deriveKnowledgeSignal(f.org.id, r.id)).issueId!; let issue = await updateIssue(f.owner.id, f.org.id, issueId, { expectedRevision: 0, status: 'REVIEWING' }); issue = await updateIssue(f.owner.id, f.org.id, issueId, { expectedRevision: issue.revision, status: 'FIX_PROPOSED', candidateVersionId: v.id, note: 'Annual coverage' }); return { f, p, v, r, g, issue }; }
async function snapshot(orgId: string) { return { tickets: await prisma.ticket.findMany({ where: { organizationId: orgId }, orderBy: { id: 'asc' } }), messages: await prisma.ticketMessage.findMany({ where: { ticket: { organizationId: orgId } }, orderBy: { id: 'asc' } }), activities: await prisma.activityLog.findMany({ where: { organizationId: orgId }, orderBy: { id: 'asc' } }), runs: await prisma.copilotRun.findMany({ where: { organizationId: orgId }, orderBy: { id: 'asc' } }), decisions: await prisma.copilotEvaluation.findMany({ where: { copilotRun: { organizationId: orgId } }, orderBy: { id: 'asc' } }), signals: await prisma.knowledgeIssueSignal.findMany({ where: { issue: { organizationId: orgId } }, orderBy: { id: 'asc' } }), issues: await prisma.knowledgeIssue.findMany({ where: { organizationId: orgId }, orderBy: { id: 'asc' } }) }; }
test('READY replay is isolated, immutable, free of provider calls and invisible to production', async () => { const { f, v, r, issue } = await setup(); const suite = await createSuite(f.owner.id, f.org.id, { name: 'Issue suite', issueId: issue.id }); expect(suite._count.cases).toBe(2); await prisma.ticket.update({ where: { id: f.ticket.id }, data: { title: 'Changed later' } }); const before = await snapshot(f.org.id), spy = jest.spyOn(provider, 'generateWithProviders'), embedding = jest.spyOn(vector, 'searchKnowledgeChunksByVector'), socket = jest.spyOn(realtime, 'emitTicketMessageCreated'); const e = await createExperiment(f.owner.id, f.org.id, { name: 'Candidate', suiteId: suite.id, purpose: 'PRE_PUBLICATION', overrideVersionIds: [v.id] }); const result = await executeExperiment(f.owner.id, f.org.id, e.id); expect(result.status).toBe('COMPLETED'); expect(result.summary).toMatchObject({ failures: { passed: 1, total: 1 }, guardrails: { preserved: 1, total: 1 } }); expect(result.suite.cases.find(c => c.historicalCopilotRunId === r.id)?.input).toMatchObject({ ticket: { title: 'Annual refund eligibility' } }); expect(await snapshot(f.org.id)).toEqual(before); expect(spy).not.toHaveBeenCalled(); expect(embedding).not.toHaveBeenCalled(); expect(socket).not.toHaveBeenCalled(); socket.mockRestore(); spy.mockRestore(); embedding.mockRestore(); expect((await retrieveHybrid(f.org.id, 'Annual refund eligibility', 5)).selectedEvidence.some(s => s.documentVersionId === v.id)).toBe(false); await expect(prisma.evaluationCase.update({ where: { id: result.suite.cases[0].id }, data: { input: {} } })).rejects.toThrow(); await expect(prisma.evaluationResult.update({ where: { id: result.results[0].id }, data: { candidate: {} } })).rejects.toThrow(); await expect(prisma.knowledgeDocumentVersion.update({ where: { id: v.id }, data: { contentHash: 'changed' } })).rejects.toThrow(); await expect(prisma.knowledgeChunk.updateMany({ where: { documentVersionId: v.id }, data: { content: 'changed' } })).rejects.toThrow(); await expect(executeExperiment(f.owner.id, f.org.id, e.id)).rejects.toMatchObject({ statusCode: 409 }); await expect(verifyIssue(f.owner.id, f.org.id, issue.id, e.id)).rejects.toMatchObject({ statusCode: 409 }); });
test('only completed exact POST publication coverage verifies and writes an internal audit', async () => { const { f, p, v, issue } = await setup(), suite = await createSuite(f.admin.id, f.org.id, { name: 'Verify', issueId: issue.id }); await publishKnowledgeVersion(f.owner.id, f.org.id, p.document.id, v.id, p.version.id); const published = await updateIssue(f.owner.id, f.org.id, issue.id, { expectedRevision: issue.revision, status: 'PUBLISHED' }); const e = await createExperiment(f.admin.id, f.org.id, { name: 'Post', suiteId: suite.id, purpose: 'POST_PUBLICATION_VERIFICATION', overrideVersionIds: [v.id] }); await expect(verifyIssue(f.owner.id, f.org.id, issue.id, e.id)).rejects.toThrow(); await executeExperiment(f.owner.id, f.org.id, e.id); await expect(updateIssue(f.owner.id, f.org.id, issue.id, { expectedRevision: published.revision, status: 'VERIFIED' })).rejects.toMatchObject({ statusCode: 409 }); const before = await snapshot(f.org.id); const verified = await verifyIssue(f.admin.id, f.org.id, issue.id, e.id); expect(verified).toMatchObject({ experimentId: e.id, failureCases: 1, guardrailCases: 1 }); const after = await snapshot(f.org.id); expect({ ...after, issues: [] }).toEqual({ ...before, issues: [] }); expect(after.issues[0].status).toBe('VERIFIED'); expect(await prisma.knowledgeIssueHistory.count({ where: { issueId: issue.id, event: 'VERIFIED' } })).toBe(1); });
test('new failure signals invalidate old coverage', async () => { const { f, p, v, issue } = await setup(), suite = await createSuite(f.owner.id, f.org.id, { name: 'Old', issueId: issue.id }); await publishKnowledgeVersion(f.owner.id, f.org.id, p.document.id, v.id, p.version.id); await updateIssue(f.owner.id, f.org.id, issue.id, { expectedRevision: issue.revision, status: 'PUBLISHED' }); const e = await createExperiment(f.owner.id, f.org.id, { name: 'Post', suiteId: suite.id, purpose: 'POST_PUBLICATION_VERIFICATION', overrideVersionIds: [v.id] }); await executeExperiment(f.owner.id, f.org.id, e.id); const newRun = await historical(f); await deriveKnowledgeSignal(f.org.id, newRun.id); await expect(verifyIssue(f.owner.id, f.org.id, issue.id, e.id)).rejects.toMatchObject({ statusCode: 409 }); });
test('tenant, role, demo guards and duplicate snapshots', async () => { const { f, v, r } = await setup(), other = await fixture(); const suite = await createSuite(f.owner.id, f.org.id, { name: 'Dedup', runIds: [r.id, r.id] }); expect(suite._count.cases).toBe(1); for (const user of [f.agent, f.customer])
    await expect(createSuite(user.id, f.org.id, { name: 'Denied', runIds: [r.id] })).rejects.toMatchObject({ statusCode: 403 }); await expect(createSuite(other.owner.id, other.org.id, { name: 'Denied', runIds: [r.id] })).rejects.toThrow(); await expect(createExperiment(other.owner.id, other.org.id, { name: 'Denied', suiteId: suite.id, purpose: 'GENERAL_COMPARISON', overrideVersionIds: [v.id] })).rejects.toThrow(); const e = await createExperiment(f.owner.id, f.org.id, { name: 'Read', suiteId: suite.id, purpose: 'GENERAL_COMPARISON' }); expect((await getExperiment(f.agent.id, f.org.id, e.id)).id).toBe(e.id); await expect(getExperiment(f.customer.id, f.org.id, e.id)).rejects.toMatchObject({ statusCode: 403 }); await expect(getExperiment(other.owner.id, other.org.id, e.id)).rejects.toMatchObject({ statusCode: 404 }); const old = process.env.DEMO_READONLY_EMAILS; process.env.DEMO_READONLY_EMAILS = f.owner.email; try {
    await expect(executeExperiment(f.owner.id, f.org.id, e.id)).rejects.toMatchObject({ statusCode: 403 });
}
finally {
    if (old === undefined)
        delete process.env.DEMO_READONLY_EMAILS;
    else
        process.env.DEMO_READONLY_EMAILS = old;
} await cancelExperiment(f.owner.id, f.org.id, e.id); await expect(executeExperiment(f.owner.id, f.org.id, e.id)).rejects.toMatchObject({ statusCode: 409 }); });
test('retrieval failure fails evaluation closed without production effects', async () => { const { f, v, issue } = await setup(), suite = await createSuite(f.owner.id, f.org.id, { name: 'Failure', issueId: issue.id }), e = await createExperiment(f.owner.id, f.org.id, { name: 'Error', suiteId: suite.id, purpose: 'PRE_PUBLICATION', overrideVersionIds: [v.id] }); const before = await snapshot(f.org.id), spy = jest.spyOn(lexical, 'searchLexical').mockRejectedValue(new Error('database failure')); try {
    const result = await executeExperiment(f.owner.id, f.org.id, e.id);
    expect(result.status).toBe('FAILED');
    expect(result.results.every(r => r.classification === 'ERROR')).toBe(true);
    expect(await snapshot(f.org.id)).toEqual(before);
}
finally {
    spy.mockRestore();
} });
test('guardrail sampling is deterministic and bounded', async () => { const { f, issue } = await setup(); for (let i = 0; i < 14; i++)
    await historical(f, true); const a = await issueCohort(prisma, f.org.id, issue.id), b = await issueCohort(prisma, f.org.id, issue.id); expect(a.guardrailIds).toHaveLength(10); expect(b.guardrailIds).toEqual(a.guardrailIds); });
test('generation is opt-in, evidence-gated, and provider failures retain completed error results', async () => { const { f, v, issue } = await setup(), suite = await createSuite(f.owner.id, f.org.id, { name: 'Generated', issueId: issue.id }); const e = await createExperiment(f.owner.id, f.org.id, { name: 'Generated', suiteId: suite.id, purpose: 'PRE_PUBLICATION', overrideVersionIds: [v.id], generation: true }); const before = await snapshot(f.org.id); const spy = jest.spyOn(provider, 'generateWithProviders').mockRejectedValue(new Error('provider outage')); try {
    const result = await executeExperiment(f.owner.id, f.org.id, e.id);
    expect(spy).toHaveBeenCalledTimes(2);
    expect(result.status).toBe('FAILED');
    expect(result.results).toHaveLength(2);
    expect(result.results.every(r => r.classification === 'ERROR')).toBe(true);
    expect(await snapshot(f.org.id)).toEqual(before);
}
finally {
    spy.mockRestore();
} const empty = await fixture(), r = await historical(empty), emptySuite = await createSuite(empty.owner.id, empty.org.id, { name: 'No evidence', runIds: [r.id] }), emptyExperiment = await createExperiment(empty.owner.id, empty.org.id, { name: 'Gated', suiteId: emptySuite.id, purpose: 'GENERAL_COMPARISON', generation: true }); const gate = jest.spyOn(provider, 'generateWithProviders'); try {
    const result = await executeExperiment(empty.owner.id, empty.org.id, emptyExperiment.id);
    expect(gate).not.toHaveBeenCalled();
    expect(result.results[0].candidate).toMatchObject({ decision: 'INSUFFICIENT_KNOWLEDGE', suggestedReply: null });
}
finally {
    gate.mockRestore();
} });
test('50-case retrieval benchmark and strict suite / generation caps', async () => { const f = await fixture(); await publication(f); const ids: string[] = []; for (let i = 0; i < 50; i++)
    ids.push((await historical(f, true)).id); const suite = await createSuite(f.owner.id, f.org.id, { name: '50-case benchmark', runIds: ids }); await expect(createExperiment(f.owner.id, f.org.id, { name: 'Too costly', suiteId: suite.id, purpose: 'GENERAL_COMPARISON', generation: true })).rejects.toMatchObject({ statusCode: 400 }); const e = await createExperiment(f.owner.id, f.org.id, { name: '50 lexical', suiteId: suite.id, purpose: 'GENERAL_COMPARISON' }); const spy = jest.spyOn(provider, 'generateWithProviders'), embedding = jest.spyOn(vector, 'searchKnowledgeChunksByVector'); const start = Date.now(); try {
    const result = await executeExperiment(f.owner.id, f.org.id, e.id);
    expect(result.status).toBe('COMPLETED');
    expect(result.results).toHaveLength(50);
    expect(spy).not.toHaveBeenCalled();
    expect(embedding).not.toHaveBeenCalled();
    const latencies = result.results.map(r => r.durationMs).sort((a, b) => a - b);
    console.log({ event: 'reliability.benchmark', cases: 50, totalMs: Date.now() - start, caseMedianMs: latencies[25], caseP95Ms: latencies[47], maxCaseMs: latencies[49] });
}
finally {
    spy.mockRestore();
    embedding.mockRestore();
} }, 60000);
test('an experiment cannot verify a later published version', async () => { const { f, p, v, issue } = await setup(), suite = await createSuite(f.owner.id, f.org.id, { name: 'Scope', issueId: issue.id }); await publishKnowledgeVersion(f.owner.id, f.org.id, p.document.id, v.id, p.version.id); await updateIssue(f.owner.id, f.org.id, issue.id, { expectedRevision: issue.revision, status: 'PUBLISHED' }); const e = await createExperiment(f.owner.id, f.org.id, { name: 'Post', suiteId: suite.id, purpose: 'POST_PUBLICATION_VERIFICATION', overrideVersionIds: [v.id] }); await executeExperiment(f.owner.id, f.org.id, e.id); const newer = await prisma.knowledgeDocumentVersion.create({ data: { documentId: p.document.id, versionNumber: 3, status: 'READY', createdByIdentity: f.owner.id, semanticIndexedChunks: 0, originalName: 'v3', mimeType: 'text/plain', sizeBytes: 10, storageRef: 'fixture', contentHash: contentHash('Annual refund eligibility policy') } }); await prisma.knowledgeChunk.create({ data: { organizationId: f.org.id, documentId: p.document.id, documentVersionId: newer.id, chunkIndex: 0, tokenCount: 4, contentHash: contentHash('Annual refund eligibility policy'), content: 'Annual refund eligibility policy' } }); await publishKnowledgeVersion(f.owner.id, f.org.id, p.document.id, newer.id, v.id); await expect(verifyIssue(f.owner.id, f.org.id, issue.id, e.id)).rejects.toMatchObject({ statusCode: 409 }); });
test('a regressed guardrail blocks verification despite an improved failure', async () => { const { f, p, v, issue } = await setup(); await historical(f, true, 'monthly cancellation billing cycle'); const suite = await createSuite(f.owner.id, f.org.id, { name: 'Regression', issueId: issue.id }); await publishKnowledgeVersion(f.owner.id, f.org.id, p.document.id, v.id, p.version.id); await updateIssue(f.owner.id, f.org.id, issue.id, { expectedRevision: issue.revision, status: 'PUBLISHED' }); const e = await createExperiment(f.owner.id, f.org.id, { name: 'Regressed', suiteId: suite.id, purpose: 'POST_PUBLICATION_VERIFICATION', overrideVersionIds: [v.id] }); const result = await executeExperiment(f.owner.id, f.org.id, e.id); expect(result.results.some(r => r.classification === 'REGRESSED')).toBe(true); await expect(verifyIssue(f.owner.id, f.org.id, issue.id, e.id)).rejects.toMatchObject({ statusCode: 409 }); });
test('overrides replace one document; other publications remain; explicit superseded replay and tenant rejection', async () => { const { f, p, v } = await setup(), other = await setup(), r = await historical(f), suite = await createSuite(f.owner.id, f.org.id, { name: 'Scope', runIds: [r.id] }); const extra = await publication(f); const e = await createExperiment(f.owner.id, f.org.id, { name: 'Scope', suiteId: suite.id, purpose: 'GENERAL_COMPARISON', overrideVersionIds: [v.id] }); expect(e.scope.map(s => s.documentVersionId).sort()).toEqual([v.id, extra.version.id].sort()); await expect(createExperiment(f.owner.id, f.org.id, { name: 'Tenant attack', suiteId: suite.id, purpose: 'GENERAL_COMPARISON', overrideVersionIds: [other.v.id] })).rejects.toMatchObject({ statusCode: 400 }); await expect(prisma.evaluationCase.create({ data: { suiteId: suite.id, historicalCopilotRunId: other.r.id, kind: 'HISTORICAL', input: {}, baseline: {} } })).rejects.toThrow(); await publishKnowledgeVersion(f.owner.id, f.org.id, p.document.id, v.id, p.version.id); const old = await createExperiment(f.owner.id, f.org.id, { name: 'Superseded comparison', suiteId: suite.id, purpose: 'GENERAL_COMPARISON', overrideVersionIds: [p.version.id] }); const result = await executeExperiment(f.owner.id, f.org.id, old.id); expect(result.status).toBe('COMPLETED'); expect(result.scope.find(s => s.documentVersionId === p.version.id)?.version.status).toBe('SUPERSEDED'); });
test('cancellation preserves completed cases and cannot be mistaken for completion', async () => { const { f, v, issue } = await setup(), suite = await createSuite(f.owner.id, f.org.id, { name: 'Cancel', issueId: issue.id }), e = await createExperiment(f.owner.id, f.org.id, { name: 'Cancel', suiteId: suite.id, purpose: 'PRE_PUBLICATION', overrideVersionIds: [v.id] }); const successor = await createExperiment(f.owner.id, f.org.id, {name:'Successor',suiteId:suite.id,purpose:'PRE_PUBLICATION',overrideVersionIds:[v.id]}); const real = lexical.searchLexical; let calls = 0; const spy = jest.spyOn(lexical, 'searchLexical').mockImplementation(async (...args) => { calls++; if (calls === 2) { await cancelExperiment(f.owner.id, f.org.id, e.id); await expect(executeExperiment(f.owner.id,f.org.id,successor.id)).rejects.toMatchObject({statusCode:409}); } return real(...args); }); try {
    const result = await executeExperiment(f.owner.id, f.org.id, e.id);
    expect(result.status).toBe('CANCELLED');
    expect(result.results).toHaveLength(1); expect(result.summary).toMatchObject({completed:1,total:2});
    await expect(verifyIssue(f.owner.id, f.org.id, issue.id, e.id)).rejects.toThrow();
}
finally {
    spy.mockRestore();
} });
test('zero guardrail coverage cannot verify a published fix',async()=>{const f=await fixture(),p=await publication(f),v=await candidate(f,p.document.id),r=await historical(f);const issueId=(await deriveKnowledgeSignal(f.org.id,r.id)).issueId!;let issue=await updateIssue(f.owner.id,f.org.id,issueId,{expectedRevision:0,status:'REVIEWING'});issue=await updateIssue(f.owner.id,f.org.id,issueId,{expectedRevision:issue.revision,status:'FIX_PROPOSED',candidateVersionId:v.id,note:'Fix'});const suite=await createSuite(f.owner.id,f.org.id,{name:'No guardrail',issueId});await publishKnowledgeVersion(f.owner.id,f.org.id,p.document.id,v.id,p.version.id);await updateIssue(f.owner.id,f.org.id,issueId,{expectedRevision:issue.revision,status:'PUBLISHED'});const e=await createExperiment(f.owner.id,f.org.id,{name:'No guardrail',suiteId:suite.id,purpose:'POST_PUBLICATION_VERIFICATION',overrideVersionIds:[v.id]});const result=await executeExperiment(f.owner.id,f.org.id,e.id);expect(result.status).toBe('COMPLETED');await expect(verifyIssue(f.owner.id,f.org.id,issueId,e.id)).rejects.toMatchObject({statusCode:409});});
