import { Router } from "express";
import { authenticate, type AuthenticatedRequest } from "../../common/middleware/auth.middleware.js";
import { asyncHandler } from "../../common/utils/asyncHandler.js";
import { requireOrgRole } from "../organizations/org.rbac.js";
import { blockDemoWrites } from "../../common/middleware/demoReadOnly.middleware.js";
import { createSuite, createExperiment, listSuites, listExperiments, getExperiment } from "./replay.service.js";
import { executeExperiment, cancelExperiment, verifyIssue } from "./replay.execution.js";
import { registry } from "./replay.schema.js";
export const reliabilityRoutes = Router({ mergeParams: true });
reliabilityRoutes.use(authenticate, requireOrgRole(['OWNER', 'ADMIN', 'AGENT']));
const id = (req: AuthenticatedRequest, key: string) => String(req.params[key]);
reliabilityRoutes.get('/configurations', (_req, res) => res.json({ data: registry }));
reliabilityRoutes.get('/suites', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await listSuites(req.user!.id, id(req, 'orgId'), Number(req.query.page ?? 1)) }); }));
reliabilityRoutes.get('/experiments', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await listExperiments(req.user!.id, id(req, 'orgId'), req.query) }); }));
reliabilityRoutes.get('/experiments/:experimentId', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await getExperiment(req.user!.id, id(req, 'orgId'), id(req, 'experimentId')) }); }));
reliabilityRoutes.use(requireOrgRole(['OWNER', 'ADMIN']), blockDemoWrites());
reliabilityRoutes.post('/suites', asyncHandler(async (req: AuthenticatedRequest, res) => { res.status(201).json({ data: await createSuite(req.user!.id, id(req, 'orgId'), req.body) }); }));
reliabilityRoutes.post('/experiments', asyncHandler(async (req: AuthenticatedRequest, res) => { res.status(201).json({ data: await createExperiment(req.user!.id, id(req, 'orgId'), req.body) }); }));
reliabilityRoutes.post('/experiments/:experimentId/execute', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await executeExperiment(req.user!.id, id(req, 'orgId'), id(req, 'experimentId')) }); }));
reliabilityRoutes.post('/experiments/:experimentId/cancel', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await cancelExperiment(req.user!.id, id(req, 'orgId'), id(req, 'experimentId')) }); }));
reliabilityRoutes.post('/issues/:issueId/verify/:experimentId', asyncHandler(async (req: AuthenticatedRequest, res) => { res.json({ data: await verifyIssue(req.user!.id, id(req, 'orgId'), id(req, 'issueId'), id(req, 'experimentId')) }); }));
