import { useMemo, useState } from "react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import {
  type OrganizationListItem,
  type Role,
  useCreateOrganizationMutation,
  useListOrganizationsQuery
} from "./orgApi";
import "./organizations.css";

export function OrganizationsPage() {
  const [name, setName] = useState("");
  const [message, setMessage] = useState("");
  const [formError, setFormError] = useState("");

  const {
    data,
    isLoading,
    isError
  } = useListOrganizationsQuery();

  const [createOrganization, { isLoading: isCreating }] =
    useCreateOrganizationMutation();

  const organizations = data?.data.organizations ?? [];

  const counts = useMemo(() => {
    return {
      total: organizations.length,
      owned: organizations.filter((item) => item.role === "OWNER").length,
      admin: organizations.filter((item) => item.role === "ADMIN").length
    };
  }, [organizations]);

  async function handleCreateOrganization(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const trimmedName = name.trim();

    if (!trimmedName) {
      setFormError("Please enter an organization name.");
      return;
    }

    setFormError("");
    setMessage("");

    try {
      await createOrganization({
        name: trimmedName
      }).unwrap();

      setName("");
      setMessage("Organization created successfully.");
    } catch (error) {
      console.error("Failed to create organization:", error);
      setFormError("Failed to create organization. Please try again.");
    }
  }

  return (
    <main className="app-page org-page">
      <header className="siq-page-header">
        <div className="siq-page-title">
          <p className="org-eyebrow">Workspace Admin</p>
          <h1>Organizations</h1>
          <p>
            Create and manage support workspaces, members, and role-based access.
          </p>
        </div>

        <div className="siq-toolbar">
          <Link to="/dashboard" className="siq-button">
            Dashboard
          </Link>

          <Link to="/tickets" className="siq-button siq-button-primary">
            View Tickets
          </Link>
        </div>
      </header>

      <section className="org-main-grid">
        <section className="siq-card org-create-card">
          <div className="org-create-icon">+</div>

          <h2>Create organization</h2>
          <p>
            Each organization has its own tickets, members, knowledge base, and
            support analytics.
          </p>

          <form onSubmit={handleCreateOrganization} className="org-form">
            {formError && <p className="org-error-message">{formError}</p>}
            {message && <p className="org-success-message">{message}</p>}

            <div className="org-field">
              <label htmlFor="org-name">Organization name</label>
              <input
                id="org-name"
                value={name}
                onChange={(event) => {
                  setName(event.target.value);
                  setFormError("");
                  setMessage("");
                }}
                placeholder="Example: Acme Support"
                maxLength={80}
              />
              <small>
                Use a clear workspace name. A URL-friendly slug is generated by
                the backend.
              </small>
            </div>

            <button
              type="submit"
              className="siq-button siq-button-primary"
              disabled={isCreating || !name.trim()}
            >
              {isCreating ? "Creating..." : "Create organization"}
            </button>
          </form>
        </section>

        <section className="siq-card org-list-card">
          <div className="org-list-top">
            <div>
              <h2>Your organizations</h2>
              <p>
                {counts.total} workspace{counts.total === 1 ? "" : "s"} ·{" "}
                {counts.owned} owned · {counts.admin} admin access
              </p>
            </div>

            {isLoading && <span className="siq-badge siq-badge-blue">Loading</span>}
          </div>

          {isError && (
            <div className="org-alert org-alert-error">
              Failed to load organizations.
            </div>
          )}

          {!isLoading && !isError && organizations.length === 0 && (
            <div className="org-empty-state">
              <strong>No organizations yet</strong>
              <p>Create your first workspace to start using SupportIQ.</p>
            </div>
          )}

          {organizations.length > 0 && (
            <div className="org-card-grid">
              {organizations.map((item) => (
                <OrganizationCard key={item.organization.id} item={item} />
              ))}
            </div>
          )}
        </section>
      </section>
    </main>
  );
}

function OrganizationCard({ item }: { item: OrganizationListItem }) {
  return (
    <article className="org-card">
      <div className="org-card-top">
        <div>
          <h3>{item.organization.name}</h3>
          <p>Workspace slug: {item.organization.slug}</p>
        </div>

        <RoleBadge role={item.role} />
      </div>

      <div className="org-meta-grid">
        <div className="org-meta-box">
          <span>Created</span>
          <strong>{formatDate(item.organization.createdAt)}</strong>
        </div>

        <div className="org-meta-box">
          <span>Updated</span>
          <strong>{formatDate(item.organization.updatedAt)}</strong>
        </div>
      </div>

      <div className="org-card-actions">
        <Link
          to={`/organizations/${item.organization.id}/members`}
          className="siq-button siq-button-primary"
        >
          Manage members
        </Link>

        <Link to="/tickets" className="siq-button">
          Open tickets
        </Link>

        <Link to="/knowledge-base" className="siq-button">
          Knowledge base
        </Link>
      </div>
    </article>
  );
}

function RoleBadge({ role }: { role: Role }) {
  return (
    <span className={`siq-badge org-role-${role.toLowerCase()}`}>
      {formatLabel(role)}
    </span>
  );
}

function formatLabel(value: string) {
  return value
    .toLowerCase()
    .split("_")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(" ");
}

function formatDate(value: string) {
  return new Date(value).toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric"
  });
}